apiVersion: v1
kind: PersistentVolume
metadata:
  name: jekyll-site
  namespace: development
spec:
  nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - minikube
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /site
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: standard