apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  selector:
    run: jekyll
  type: NodePort
  ports:
    - name: jekyll-ports
      protocol: TCP
      port: 8080
      nodePort: 30097
      targetPort: 4000
