apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/d/Learning/CKAD/chal2
  storageClassName: standard